### PR TITLE
Fix #9 UTF-8 encoding

### LINKED ISSUE #9: RelocationTransformer should use project.build.sourceEncoding as encoding
and pass it to IOUtils + use it in getBytes: https://github.com/yupiik/maven-shade-transformers/blob/master/src/main/java/io/yupiik/maven/shade/transformer/RelocationTransformer.java#L65

also maybe allow to overwrite

### PR DESCRIPTION
**Pull request by melloware**
It looks like the Maven Mojo is not accessible at this point in the  code so  I have no idea how to get the source encoding like in this MOJO:
https://github.com/apache/maven-resources-plugin/blob/36c4ad7c0b3c7987944fcf749ef01f3f59fa6608/src/main/java/org/apache/maven/plugins/resources/ResourcesMojo.java#L56-L60

For now I just made it UTF-8 to be safe?

### CODE REVIEW

**Comment by rmannibucau** [comment]
@melloware add a setCharset and use the configured one, will enable consumer to configure it in the pom maybe

**Comment by melloware** [comment]
@rmannibucau I am unclear what you mean but I added a `setCharset` and default it to UTF-8 if its null?

**Comment by melloware** [comment]
Also I have confirmed this fixes the encoding issue we see in the PrimeFaces build.

**Comment by rmannibucau** [comment]
@melloware this is good for me since now in shade `<configuration>` you can set the charset explicitly. Can be worth a test but otherwise LGTM

**Comment by melloware** [comment]
@fpapon can you merge and release 0.0.4 by any chance so I can fix PrimeFaces build for users?

**Comment by fpapon** [comment]
@melloware yes I will do it today

**Review by rmannibucau — APPROVED** [review]

**Comment by melloware** [comment]
Thank you @fpapon !

**Comment by fpapon** [comment]
@melloware release is done and available on central, let me know if it works for you ;)

**Pull request merged**
